//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dfgijklWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PetInfo()
        {
            this.Owners = new HashSet<Owners>();
        }
    
        public string name { get; set; }
        public string breed { get; set; }
        public System.DateTime birthdate { get; set; }
        public int count_of_medal { get; set; }
        public int id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Owners> Owners { get; set; }
    }
}
